on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /home/runner/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulator-${{ hashFiles('./functions/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: yarn functions:install
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
